In [193]:
import numpy as np
import torch

### 1D, 2D, and 3D tensors using NumPy

In [194]:
np1 = np.array([1,2,3])
np2 = np.array([[1,2,3],[4,5,6]])
np3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"NP-1D:\n{np1}\nShape: {np1.shape}\n")
print(f"NP-2D:\n{np2}\nShape: {np2.shape}\n")
print(f"NP-3D:\n{np3}\nShape: {np3.shape}")

NP-1D:
[1 2 3]
Shape: (3,)

NP-2D:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

NP-3D:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


### 1D, 2D, and 3D tensors using PyTorch

In [195]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([[1,2,3],[4,5,6]])
t3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"Torch-1D:\n{t1}\nShape: {t1.shape}\n")
print(f"Torch-2D:\n{t2}\nShape: {t2.shape}\n")
print(f"Torch-3D:\n{t3}\nShape: {t3.shape}")

Torch-1D:
tensor([1, 2, 3])
Shape: torch.Size([3])

Torch-2D:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

Torch-3D:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape: torch.Size([2, 2, 3])


### Element-wise Addition, Subtraction, Multiplication, Division

In [196]:
x_np = np.array([1,2,3,4,5,])
y_np = np.array([10,9,8,7,6,])

x_torch = torch.tensor([1,2,3,4,5,])
y_torch = torch.tensor([10,9,8,7,6,])

print("NP Addition:", x_np + y_np)
print("Torch Addition:", x_torch + y_torch)
print("\nNP Subtraction:", y_np - x_np)
print("Torch Subtraction:", y_torch - x_torch)
print("\nNP Multiplication:", x_np * y_np)
print("Torch Multiplication:", x_torch * y_torch)
print("\nNP Division:", np.round(y_np / x_np, 4))
print("Torch Division:", y_torch / x_torch)

NP Addition: [11 11 11 11 11]
Torch Addition: tensor([11, 11, 11, 11, 11])

NP Subtraction: [9 7 5 3 1]
Torch Subtraction: tensor([9, 7, 5, 3, 1])

NP Multiplication: [10 18 24 28 30]
Torch Multiplication: tensor([10, 18, 24, 28, 30])

NP Division: [10.      4.5     2.6667  1.75    1.2   ]
Torch Division: tensor([10.0000,  4.5000,  2.6667,  1.7500,  1.2000])


### Dot Product

In [197]:
x_np = np.array([1,2,3,4,5,])
y_np = np.array([10,9,8,7,6,])

x_torch = torch.tensor([1,2,3,4,5,])
y_torch = torch.tensor([10,9,8,7,6,])

print("NP Dot Product:", np.dot(x_np,y_np))
print("Torch Dot Product:", torch.dot(x_torch,y_torch))

NP Dot Product: 110
Torch Dot Product: tensor(110)


### Matrix Multiplication

In [198]:
x_np = np.array([[1, 2],[3, 4]])
y_np = np.array([[5, 6],[7, 8]])

x_torch = torch.tensor([[1, 2],[3, 4]])
y_torch = torch.tensor([[5, 6],[7, 8]])

print("NP Matrix Multiplication:\n", np.matmul(x_np,y_np))
print("Torch Matrix Multiplication:\n", torch.matmul(x_torch,y_torch))

NP Matrix Multiplication:
 [[19 22]
 [43 50]]
Torch Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


### Indexing & Slicing

In [199]:
x_np = np.array([1,2,3,4,5,])
x_torch = torch.tensor([1,2,3,4,5,])

print("NP Index:", x_np[2])
print("Torch Index:", x_torch[2])
print("\nNP Slice:", x_np[1:4])
print("Torch Slice:", x_torch[1:4])

NP Index: 3
Torch Index: tensor(3)

NP Slice: [2 3 4]
Torch Slice: tensor([2, 3, 4])


### Boolean Masking

In [200]:
x_np = np.array([[1,2,3],[4,5,6]])
mask_np = x_np % 2 == 1

x_torch = torch.tensor([[1,2,3],[4,5,6]])
mask_torch = x_np % 2 == 0

print("NP Mask Value:\n",mask_np)
print("NP Masked:",x_np[mask_np])
print("\nTorch Mask Value:\n",mask_torch)
print("Torch Masked:",x_torch[mask_torch])

NP Mask Value:
 [[ True False  True]
 [False  True False]]
NP Masked: [1 3 5]

Torch Mask Value:
 [[False  True False]
 [ True False  True]]
Torch Masked: tensor([2, 4, 6])


### Extracting Subtensors

In [201]:
x_np = np.array([[1,2,3],[4,5,6],[7,8,9]])
x_torch = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print("NP Subtensor:\n", x_np[0:2,1:3]) #x[a:b,c:d] = [Select Rows from row a to row b-1, Select cols from col c to col d-1]
print("Torch Subtensor:\n", x_torch[1:2,1:2])

NP Subtensor:
 [[2 3]
 [5 6]]
Torch Subtensor:
 tensor([[5]])


### .view(), .reshape(), .unsqueeze(), .squeeze() in PyTorch

In [202]:
x_torch = torch.arange(1,11)
print("Original Tensor:",x_torch)

x_torch_view = x_torch.view(2, 5)
print("Tensor View:\n",x_torch_view)

x_torch_reshape = x_torch.reshape(2, 5)
print("Tensor Reshape:\n",x_torch_reshape)

Original Tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Tensor View:
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Tensor Reshape:
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [203]:
x_torch = torch.tensor([[[1,2,3],[4,5,6]]])
print("Original Tensor (1x2x3):\n",x_torch)
print("\nTensor Squeeze at Dim = 0 (2x3):\n",x_torch.squeeze(0))
print("Tensor Squeeze at Dim = 1 (1x2x3):\n",x_torch.squeeze(1))
print("\nTensor Unsqueeze at Dim = 0 (1x1x2x3):\n",x_torch.unsqueeze(0))
print("Tensor Unsqueeze at Dim = 1 (1x1x2x3):\n",x_torch.unsqueeze(1))
print("Tensor Unsqueeze at Dim = 2 (1x2x1x3):\n",x_torch.unsqueeze(2))
print("Tensor Unsqueeze at Dim = 3 (1x2x3x1):\n",x_torch.unsqueeze(3))

Original Tensor (1x2x3):
 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Tensor Squeeze at Dim = 0 (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor Squeeze at Dim = 1 (1x2x3):
 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Tensor Unsqueeze at Dim = 0 (1x1x2x3):
 tensor([[[[1, 2, 3],
          [4, 5, 6]]]])
Tensor Unsqueeze at Dim = 1 (1x1x2x3):
 tensor([[[[1, 2, 3],
          [4, 5, 6]]]])
Tensor Unsqueeze at Dim = 2 (1x2x1x3):
 tensor([[[[1, 2, 3]],

         [[4, 5, 6]]]])
Tensor Unsqueeze at Dim = 3 (1x2x3x1):
 tensor([[[[1],
          [2],
          [3]],

         [[4],
          [5],
          [6]]]])


### .reshape() PyTorch vs Numpy

In [204]:
x_np = np.arange(1,11)
print("NP:",x_np)
x_np_reshape = x_np.reshape(2, 5)
print("NP Reshape:\n",x_np_reshape)

x_torch = torch.arange(1,11)
print("\nTorch:",x_torch)
x_torch_reshape = x_torch.reshape(2, 5)
print("Torch Reshape:\n",x_torch_reshape)

NP: [ 1  2  3  4  5  6  7  8  9 10]
NP Reshape:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Torch: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Torch Reshape:
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


### Broadcasting

In [205]:
x_np = np.array([[1, 2, 3],[4, 5, 6]])
y_np = np.array([19, 18, 17])
print("NP Broadcasting:\n", x_np + y_np)

x_torch = torch.tensor([[1, 2, 3],[4, 5, 6]])
y_torch = torch.tensor([19, 18, 17])
print("Torch Broadcasting:\n", x_torch + y_torch)

NP Broadcasting:
 [[20 20 20]
 [23 23 23]]
Torch Broadcasting:
 tensor([[20, 20, 20],
        [23, 23, 23]])


### In-place Operations

In [206]:
x_np = np.array([[1, 2, 3],[4,5,6]])
id1_np = id(x_np)
print("NP Before Inplace operation:\n",x_np)
print("ID Before Inplace operation:\n",id1_np)
x_np *= 10
id2_np = id(x_np)
print("NP After Inplace operation:\n",x_np)
print("ID After Inplace operation:\n",id2_np)
print("Same Array Modified:", id1_np==id2_np)

x_torch = torch.tensor([[10, 15, 20],[25,30,35]])
id1_torch = id(x_torch)
print("\nTorch Before Inplace operation:\n",x_torch)
print("ID Before Inplace operation:\n",id1_torch)
x_torch *= 10
id2_torch = id(x_torch)
print("Torch After Inplace operation:\n",x_torch)
print("ID After Inplace operation:\n",id2_torch)
print("Same Tensor Modified:", id1_torch==id2_torch)


NP Before Inplace operation:
 [[1 2 3]
 [4 5 6]]
ID Before Inplace operation:
 1403457469968
NP After Inplace operation:
 [[10 20 30]
 [40 50 60]]
ID After Inplace operation:
 1403457469968
Same Array Modified: True

Torch Before Inplace operation:
 tensor([[10, 15, 20],
        [25, 30, 35]])
ID Before Inplace operation:
 1403396652432
Torch After Inplace operation:
 tensor([[100, 150, 200],
        [250, 300, 350]])
ID After Inplace operation:
 1403396652432
Same Tensor Modified: True


### Out-of-place Operations

In [207]:
x_np = np.array([[1, 2, 3],[4,5,6]])
id1_np = id(x_np)
print("NP Before Out-of-place operation:\n",x_np)
print("ID Before Out-of-place operation:\n",id1_np)
y_np = x_np * 10
id2_np = id(y_np)
print("NP After Out-of-place operation:\n",x_np)
print("ID After Out-of-place operation:\n",id2_np)
print("Same Array Modified:", id1_np==id2_np)

x_torch = torch.tensor([[10, 15, 20],[25,30,35]])
id1_torch = id(x_torch)
print("\nTorch Before Out-of-place operation:\n",x_torch)
print("ID Before Out-of-place operation:\n",id1_torch)
y_torch = x_torch * 10
id2_torch = id(y_torch)
print("Torch After Out-of-place operation:\n",x_torch)
print("ID After Out-of-place operation:\n",id2_torch)
print("Same Tensor Modified:", id1_torch==id2_torch)


NP Before Out-of-place operation:
 [[1 2 3]
 [4 5 6]]
ID Before Out-of-place operation:
 1403456994352
NP After Out-of-place operation:
 [[1 2 3]
 [4 5 6]]
ID After Out-of-place operation:
 1403407727760
Same Array Modified: False

Torch Before Out-of-place operation:
 tensor([[10, 15, 20],
        [25, 30, 35]])
ID Before Out-of-place operation:
 1403456606272
Torch After Out-of-place operation:
 tensor([[10, 15, 20],
        [25, 30, 35]])
ID After Out-of-place operation:
 1403396652432
Same Tensor Modified: False
